In [3]:
# Pandas is a Python library used to read and work with data.
# pd is just a short name used to make coding easier.

import pandas as pd

In [5]:
# This line reads the salary data from a CSV file and stores it in a variable called dataset.

dataset=pd.read_csv("Salary_Data.csv")

In [6]:
# This command displays the dataset.

dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [7]:
# Here the input column YearsExperience is selected and stored in a variable named independent. 

independent=dataset[["YearsExperience"]]
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [8]:
# Here the output column Salary is selected and stored in a variable named dependent. 

dependent=dataset[["Salary"]]
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [9]:
# sklearn is a machine learning library in Python used to build, train, and test models easily.
# Here, using the sklearn library the dataset is split into training and testing data.
# 70% of the data is used to train the model and 30% is used to test it.

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [10]:
# A Linear Regression model is created and trained using the training data.

from sklearn.linear_model import LinearRegression # imports the Linear Regression model from the sklearn library.
regressor=LinearRegression() #  creates a Linear Regression model and stores it in the variable named regressor.
regressor.fit(X_train,y_train) # trains the model using the training input (X_train) and output (y_train) data.

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
weight=regressor.coef_  #  This line gets the weight (coefficient) value from the trained model.
weight # displays the weight value

array([[9360.26128619]])

In [13]:
bias=regressor.intercept_  # This line gets the bias (intercept) value from the trained model.
bias # displays the bias value

array([26777.3913412])

In [15]:
# Predicts the salary for the test data using the trained model.

y_pred=regressor.predict(X_test)

In [16]:
from sklearn.metrics import r2_score # Imports the r2_score function from the sklearn.metrics module
r_score=r2_score(y_test,y_pred) # Computes the R² score by comparing actual and predicted values.

In [17]:
r_score # Displays the R² score of the model.

0.9740993407213511

In [18]:
import pickle # Imports the pickle module, used to save Python objects (like models).
filename="finalized_model_linear.sav" # Defines the filename to save the trained model.

In [19]:
pickle.dump(regressor,open(filename,'wb')) # Saves the trained model (regressor) to a file in binary mode ('wb')
                                           # using pickle.dump().

In [20]:
loaded_model=pickle.load(open("finalized_model_linear.sav", 'rb')) # Loads the saved model from the file in read-binary mode ('rb') 
                                                                   # using pickle.load()
result=loaded_model.predict([[13]]) # Uses the loaded model to predict the salary for 13 years of experience.

In [21]:
result # Displays the predicted salary for 13 years of experience.

array([[148460.78806172]])