In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset, drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
independent= dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent= dataset['charges']
dependent

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR

# Define the Pipeline (Scales data then applies SVR)
pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('svr', SVR())
])

In [9]:
# Update param_grid to match Pipeline keys (note the 'svr__' prefix)
param_grid = {
    'svr__kernel': ['rbf', 'poly', 'sigmoid', 'linear'],
    'svr__C': [10, 100, 1000, 2000, 3000],
    'svr__gamma': ['auto', 'scale']
}

In [10]:
#  Fit on the entire dataset (independent, dependent)
grid = GridSearchCV(pipe, param_grid, refit=True, verbose=3, n_jobs=1) # n_jobs=-1 makes it faster
grid.fit(independent, dependent)

Fitting 5 folds for each of 40 candidates, totalling 200 fits
[CV 1/5] END svr__C=10, svr__gamma=auto, svr__kernel=rbf;, score=-0.049 total time=   0.0s
[CV 2/5] END svr__C=10, svr__gamma=auto, svr__kernel=rbf;, score=-0.046 total time=   0.0s
[CV 3/5] END svr__C=10, svr__gamma=auto, svr__kernel=rbf;, score=-0.017 total time=   0.1s
[CV 4/5] END svr__C=10, svr__gamma=auto, svr__kernel=rbf;, score=-0.041 total time=   0.0s
[CV 5/5] END svr__C=10, svr__gamma=auto, svr__kernel=rbf;, score=-0.048 total time=   0.0s
[CV 1/5] END svr__C=10, svr__gamma=auto, svr__kernel=poly;, score=0.050 total time=   0.0s
[CV 2/5] END svr__C=10, svr__gamma=auto, svr__kernel=poly;, score=0.034 total time=   0.0s
[CV 3/5] END svr__C=10, svr__gamma=auto, svr__kernel=poly;, score=0.061 total time=   0.0s
[CV 4/5] END svr__C=10, svr__gamma=auto, svr__kernel=poly;, score=0.045 total time=   0.0s
[CV 5/5] END svr__C=10, svr__gamma=auto, svr__kernel=poly;, score=0.038 total time=   0.0s
[CV 1/5] END svr__C=10, svr__gamma=auto, svr__kernel=sigmoid;, score=0.032 total time=   0.0s
[CV 2/5] END svr__C=10, svr__gamma=auto, svr__kernel=sigmoid;, score=0.041 total time=   0.0s
[CV 3/5] END svr__C=10, svr__gamma=auto, svr__kernel=sigmoid;, score=0.059 total time=   0.0s
[CV 4/5] END svr__C=10, svr__gamma=auto, svr__kernel=sigmoid;, score=0.041 total time=   0.0s
[CV 5/5] END svr__C=10, svr__gamma=auto, svr__kernel=sigmoid;, score=0.019 total time=   0.0s
[CV 1/5] END svr__C=10, svr__gamma=auto, svr__kernel=linear;, score=0.493 total time=   0.0s
[CV 2/5] END svr__C=10, svr__gamma=auto, svr__kernel=linear;, score=0.465 total time=   0.0s
[CV 3/5] END svr__C=10, svr__gamma=auto, svr__kernel=linear;, score=0.482 total time=   0.0s
[CV 4/5] END svr__C=10, svr__gamma=auto, svr__kernel=linear;, score=0.476 total time=   0.0s
[CV 5/5] END svr__C=10, svr__gamma=auto, svr__kernel=linear;, score=0.450 total time=   0.0s
[CV 1/5] END svr__C=10, svr__gamma=scale, svr__kernel=rbf;, score=-0.049 total time=   0.0s
[CV 2/5] END svr__C=10, svr__gamma=scale, svr__kernel=rbf;, score=-0.046 total time=   0.0s
[CV 3/5] END svr__C=10, svr__gamma=scale, svr__kernel=rbf;, score=-0.017 total time=   0.1s
[CV 4/5] END svr__C=10, svr__gamma=scale, svr__kernel=rbf;, score=-0.041 total time=   0.0s
[CV 5/5] END svr__C=10, svr__gamma=scale, svr__kernel=rbf;, score=-0.048 total time=   0.0s
[CV 1/5] END svr__C=10, svr__gamma=scale, svr__kernel=poly;, score=0.050 total time=   0.0s
[CV 2/5] END svr__C=10, svr__gamma=scale, svr__kernel=poly;, score=0.034 total time=   0.0s
[CV 3/5] END svr__C=10, svr__gamma=scale, svr__kernel=poly;, score=0.061 total time=   0.0s
[CV 4/5] END svr__C=10, svr__gamma=scale, svr__kernel=poly;, score=0.045 total time=   0.0s
[CV 5/5] END svr__C=10, svr__gamma=scale, svr__kernel=poly;, score=0.038 total time=   0.0s
[CV 1/5] END svr__C=10, svr__gamma=scale, svr__kernel=sigmoid;, score=0.032 total time=   0.0s
[CV 2/5] END svr__C=10, svr__gamma=scale, svr__kernel=sigmoid;, score=0.041 total time=   0.0s
[CV 3/5] END svr__C=10, svr__gamma=scale, svr__kernel=sigmoid;, score=0.059 total time=   0.0s
[CV 4/5] END svr__C=10, svr__gamma=scale, svr__kernel=sigmoid;, score=0.041 total time=   0.0s
[CV 5/5] END svr__C=10, svr__gamma=scale, svr__kernel=sigmoid;, score=0.019 total time=   0.1s
[CV 1/5] END svr__C=10, svr__gamma=scale, svr__kernel=linear;, score=0.493 total time=   0.0s
[CV 2/5] END svr__C=10, svr__gamma=scale, svr__kernel=linear;, score=0.465 total time=   0.0s
[CV 3/5] END svr__C=10, svr__gamma=scale, svr__kernel=linear;, score=0.482 total time=   0.0s
[CV 4/5] END svr__C=10, svr__gamma=scale, svr__kernel=linear;, score=0.476 total time=   0.0s
[CV 5/5] END svr__C=10, svr__gamma=scale, svr__kernel=linear;, score=0.450 total time=   0.0s
[CV 1/5] END svr__C=100, svr__gamma=auto, svr__kernel=rbf;, score=0.364 total time=   0.0s
[CV 2/5] END svr__C=100, svr__gamma=auto, svr__kernel=rbf;, score=0.342 total time=   0.0s
[CV 3/5] END svr__C=100, svr__gamma=auto, svr__kernel=rbf;, score=0.359 total time=   0.0s
[CV 4/5] END svr__C=100, svr__gamma=auto, svr__kernel=rbf;, score=0.345 total time=   0.1s
[CV 5/5] END svr__C=100, svr__gamma=auto, svr__kernel=rbf;, score=0.333 total time=   0.0s
[CV 1/5] END svr__C=100, svr__gamma=auto, svr__kernel=poly;, score=0.675 total time=   0.0s
[CV 2/5] END svr__C=100, svr__gamma=auto, svr__kernel=poly;, score=0.599 total time=   0.0s
[CV 3/5] END svr__C=100, svr__gamma=auto, svr__kernel=poly;, score=0.643 total time=   0.0s
[CV 4/5] END svr__C=100, svr__gamma=auto, svr__kernel=poly;, score=0.622 total time=   0.0s
[CV 5/5] END svr__C=100, svr__gamma=auto, svr__kernel=poly;, score=0.610 total time=   0.0s
[CV 1/5] END svr__C=100, svr__gamma=auto, svr__kernel=sigmoid;, score=0.524 total time=   0.0s
[CV 2/5] END svr__C=100, svr__gamma=auto, svr__kernel=sigmoid;, score=0.491 total time=   0.0s
[CV 3/5] END svr__C=100, svr__gamma=auto, svr__kernel=sigmoid;, score=0.515 total time=   0.0s
[CV 4/5] END svr__C=100, svr__gamma=auto, svr__kernel=sigmoid;, score=0.512 total time=   0.0s
[CV 5/5] END svr__C=100, svr__gamma=auto, svr__kernel=sigmoid;, score=0.488 total time=   0.0s
[CV 1/5] END svr__C=100, svr__gamma=auto, svr__kernel=linear;, score=0.641 total time=   0.0s
[CV 2/5] END svr__C=100, svr__gamma=auto, svr__kernel=linear;, score=0.602 total time=   0.0s
[CV 3/5] END svr__C=100, svr__gamma=auto, svr__kernel=linear;, score=0.625 total time=   0.0s
[CV 4/5] END svr__C=100, svr__gamma=auto, svr__kernel=linear;, score=0.629 total time=   0.0s
[CV 5/5] END svr__C=100, svr__gamma=auto, svr__kernel=linear;, score=0.596 total time=   0.0s
[CV 1/5] END svr__C=100, svr__gamma=scale, svr__kernel=rbf;, score=0.364 total time=   0.0s
[CV 2/5] END svr__C=100, svr__gamma=scale, svr__kernel=rbf;, score=0.342 total time=   0.0s
[CV 3/5] END svr__C=100, svr__gamma=scale, svr__kernel=rbf;, score=0.359 total time=   0.0s
[CV 4/5] END svr__C=100, svr__gamma=scale, svr__kernel=rbf;, score=0.345 total time=   0.1s
[CV 5/5] END svr__C=100, svr__gamma=scale, svr__kernel=rbf;, score=0.333 total time=   0.0s
[CV 1/5] END svr__C=100, svr__gamma=scale, svr__kernel=poly;, score=0.675 total time=   0.0s
[CV 2/5] END svr__C=100, svr__gamma=scale, svr__kernel=poly;, score=0.599 total time=   0.0s
[CV 3/5] END svr__C=100, svr__gamma=scale, svr__kernel=poly;, score=0.643 total time=   0.0s
[CV 4/5] END svr__C=100, svr__gamma=scale, svr__kernel=poly;, score=0.622 total time=   0.0s
[CV 5/5] END svr__C=100, svr__gamma=scale, svr__kernel=poly;, score=0.610 total time=   0.0s
[CV 1/5] END svr__C=100, svr__gamma=scale, svr__kernel=sigmoid;, score=0.524 total time=   0.0s
[CV 2/5] END svr__C=100, svr__gamma=scale, svr__kernel=sigmoid;, score=0.491 total time=   0.0s
[CV 3/5] END svr__C=100, svr__gamma=scale, svr__kernel=sigmoid;, score=0.515 total time=   0.0s
[CV 4/5] END svr__C=100, svr__gamma=scale, svr__kernel=sigmoid;, score=0.512 total time=   0.1s
[CV 5/5] END svr__C=100, svr__gamma=scale, svr__kernel=sigmoid;, score=0.488 total time=   0.0s
[CV 1/5] END svr__C=100, svr__gamma=scale, svr__kernel=linear;, score=0.641 total time=   0.0s
[CV 2/5] END svr__C=100, svr__gamma=scale, svr__kernel=linear;, score=0.602 total time=   0.0s
[CV 3/5] END svr__C=100, svr__gamma=scale, svr__kernel=linear;, score=0.625 total time=   0.0s
[CV 4/5] END svr__C=100, svr__gamma=scale, svr__kernel=linear;, score=0.629 total time=   0.0s
[CV 5/5] END svr__C=100, svr__gamma=scale, svr__kernel=linear;, score=0.596 total time=   0.0s
[CV 1/5] END svr__C=1000, svr__gamma=auto, svr__kernel=rbf;, score=0.834 total time=   0.0s
[CV 2/5] END svr__C=1000, svr__gamma=auto, svr__kernel=rbf;, score=0.754 total time=   0.1s
[CV 3/5] END svr__C=1000, svr__gamma=auto, svr__kernel=rbf;, score=0.802 total time=   0.1s
[CV 4/5] END svr__C=1000, svr__gamma=auto, svr__kernel=rbf;, score=0.778 total time=   0.1s
[CV 5/5] END svr__C=1000, svr__gamma=auto, svr__kernel=rbf;, score=0.784 total time=   0.0s
[CV 1/5] END svr__C=1000, svr__gamma=auto, svr__kernel=poly;, score=0.851 total time=   0.0s
[CV 2/5] END svr__C=1000, svr__gamma=auto, svr__kernel=poly;, score=0.773 total time=   0.0s
[CV 3/5] END svr__C=1000, svr__gamma=auto, svr__kernel=poly;, score=0.867 total time=   0.0s

[CV 4/5] END svr__C=1000, svr__gamma=auto, svr__kernel=poly;, score=0.807 total time=   0.0s
[CV 5/5] END svr__C=1000, svr__gamma=auto, svr__kernel=poly;, score=0.808 total time=   0.0s
[CV 1/5] END svr__C=1000, svr__gamma=auto, svr__kernel=sigmoid;, score=0.139 total time=   0.0s
[CV 2/5] END svr__C=1000, svr__gamma=auto, svr__kernel=sigmoid;, score=0.125 total time=   0.1s
[CV 3/5] END svr__C=1000, svr__gamma=auto, svr__kernel=sigmoid;, score=0.174 total time=   0.0s
[CV 4/5] END svr__C=1000, svr__gamma=auto, svr__kernel=sigmoid;, score=0.117 total time=   0.0s
[CV 5/5] END svr__C=1000, svr__gamma=auto, svr__kernel=sigmoid;, score=0.055 total time=   0.0s
[CV 1/5] END svr__C=1000, svr__gamma=auto, svr__kernel=linear;, score=0.673 total time=   0.0s
[CV 2/5] END svr__C=1000, svr__gamma=auto, svr__kernel=linear;, score=0.621 total time=   0.0s
[CV 3/5] END svr__C=1000, svr__gamma=auto, svr__kernel=linear;, score=0.730 total time=   0.0s
[CV 4/5] END svr__C=1000, svr__gamma=auto, svr__kernel=linear;, score=0.632 total time=   0.0s
[CV 5/5] END svr__C=1000, svr__gamma=auto, svr__kernel=linear;, score=0.692 total time=   0.0s
[CV 1/5] END svr__C=1000, svr__gamma=scale, svr__kernel=rbf;, score=0.834 total time=   0.0s
[CV 2/5] END svr__C=1000, svr__gamma=scale, svr__kernel=rbf;, score=0.754 total time=   0.1s
[CV 3/5] END svr__C=1000, svr__gamma=scale, svr__kernel=rbf;, score=0.802 total time=   0.1s
[CV 4/5] END svr__C=1000, svr__gamma=scale, svr__kernel=rbf;, score=0.778 total time=   0.1s
[CV 5/5] END svr__C=1000, svr__gamma=scale, svr__kernel=rbf;, score=0.784 total time=   0.1s
[CV 1/5] END svr__C=1000, svr__gamma=scale, svr__kernel=poly;, score=0.851 total time=   0.0s
[CV 2/5] END svr__C=1000, svr__gamma=scale, svr__kernel=poly;, score=0.773 total time=   0.0s
[CV 3/5] END svr__C=1000, svr__gamma=scale, svr__kernel=poly;, score=0.867 total time=   0.0s
[CV 4/5] END svr__C=1000, svr__gamma=scale, svr__kernel=poly;, score=0.807 total time=   0.0s
[CV 5/5] END svr__C=1000, svr__gamma=scale, svr__kernel=poly;, score=0.808 total time=   0.0s
[CV 1/5] END svr__C=1000, svr__gamma=scale, svr__kernel=sigmoid;, score=0.139 total time=   0.0s
[CV 2/5] END svr__C=1000, svr__gamma=scale, svr__kernel=sigmoid;, score=0.125 total time=   0.0s
[CV 3/5] END svr__C=1000, svr__gamma=scale, svr__kernel=sigmoid;, score=0.174 total time=   0.0s
[CV 4/5] END svr__C=1000, svr__gamma=scale, svr__kernel=sigmoid;, score=0.117 total time=   0.0s
[CV 5/5] END svr__C=1000, svr__gamma=scale, svr__kernel=sigmoid;, score=0.055 total time=   0.0s
[CV 1/5] END svr__C=1000, svr__gamma=scale, svr__kernel=linear;, score=0.673 total time=   0.0s
[CV 2/5] END svr__C=1000, svr__gamma=scale, svr__kernel=linear;, score=0.621 total time=   0.0s
[CV 3/5] END svr__C=1000, svr__gamma=scale, svr__kernel=linear;, score=0.730 total time=   0.0s
[CV 4/5] END svr__C=1000, svr__gamma=scale, svr__kernel=linear;, score=0.632 total time=   0.0s
[CV 5/5] END svr__C=1000, svr__gamma=scale, svr__kernel=linear;, score=0.692 total time=   0.0s
[CV 1/5] END svr__C=2000, svr__gamma=auto, svr__kernel=rbf;, score=0.863 total time=   0.1s
[CV 2/5] END svr__C=2000, svr__gamma=auto, svr__kernel=rbf;, score=0.776 total time=   0.0s
[CV 3/5] END svr__C=2000, svr__gamma=auto, svr__kernel=rbf;, score=0.848 total time=   0.0s
[CV 4/5] END svr__C=2000, svr__gamma=auto, svr__kernel=rbf;, score=0.801 total time=   0.0s
[CV 5/5] END svr__C=2000, svr__gamma=auto, svr__kernel=rbf;, score=0.812 total time=   0.0s
[CV 1/5] END svr__C=2000, svr__gamma=auto, svr__kernel=poly;, score=0.852 total time=   0.0s
[CV 2/5] END svr__C=2000, svr__gamma=auto, svr__kernel=poly;, score=0.775 total time=   0.0s
[CV 3/5] END svr__C=2000, svr__gamma=auto, svr__kernel=poly;, score=0.869 total time=   0.1s
[CV 4/5] END svr__C=2000, svr__gamma=auto, svr__kernel=poly;, score=0.809 total time=   0.2s
[CV 5/5] END svr__C=2000, svr__gamma=auto, svr__kernel=poly;, score=0.809 total time=   0.1s
[CV 1/5] END svr__C=2000, svr__gamma=auto, svr__kernel=sigmoid;, score=-1.560 total time=   0.0s
[CV 2/5] END svr__C=2000, svr__gamma=auto, svr__kernel=sigmoid;, score=-1.787 total time=   0.0s
[CV 3/5] END svr__C=2000, svr__gamma=auto, svr__kernel=sigmoid;, score=-1.320 total time=   0.0s
[CV 4/5] END svr__C=2000, svr__gamma=auto, svr__kernel=sigmoid;, score=-1.460 total time=   0.0s
[CV 5/5] END svr__C=2000, svr__gamma=auto, svr__kernel=sigmoid;, score=-1.226 total time=   0.0s
[CV 1/5] END svr__C=2000, svr__gamma=auto, svr__kernel=linear;, score=0.672 total time=   0.0s
[CV 2/5] END svr__C=2000, svr__gamma=auto, svr__kernel=linear;, score=0.618 total time=   0.0s
[CV 3/5] END svr__C=2000, svr__gamma=auto, svr__kernel=linear;, score=0.729 total time=   0.0s
[CV 4/5] END svr__C=2000, svr__gamma=auto, svr__kernel=linear;, score=0.628 total time=   0.0s
[CV 5/5] END svr__C=2000, svr__gamma=auto, svr__kernel=linear;, score=0.691 total time=   0.0s
[CV 1/5] END svr__C=2000, svr__gamma=scale, svr__kernel=rbf;, score=0.863 total time=   0.0s
[CV 2/5] END svr__C=2000, svr__gamma=scale, svr__kernel=rbf;, score=0.776 total time=   0.1s
[CV 3/5] END svr__C=2000, svr__gamma=scale, svr__kernel=rbf;, score=0.848 total time=   0.0s
[CV 4/5] END svr__C=2000, svr__gamma=scale, svr__kernel=rbf;, score=0.801 total time=   0.1s
[CV 5/5] END svr__C=2000, svr__gamma=scale, svr__kernel=rbf;, score=0.812 total time=   0.0s
[CV 1/5] END svr__C=2000, svr__gamma=scale, svr__kernel=poly;, score=0.852 total time=   0.0s
[CV 2/5] END svr__C=2000, svr__gamma=scale, svr__kernel=poly;, score=0.775 total time=   0.1s
[CV 3/5] END svr__C=2000, svr__gamma=scale, svr__kernel=poly;, score=0.869 total time=   0.0s
[CV 4/5] END svr__C=2000, svr__gamma=scale, svr__kernel=poly;, score=0.809 total time=   0.1s
[CV 5/5] END svr__C=2000, svr__gamma=scale, svr__kernel=poly;, score=0.809 total time=   0.1s
[CV 1/5] END svr__C=2000, svr__gamma=scale, svr__kernel=sigmoid;, score=-1.560 total time=   0.0s
[CV 2/5] END svr__C=2000, svr__gamma=scale, svr__kernel=sigmoid;, score=-1.787 total time=   0.0s
[CV 3/5] END svr__C=2000, svr__gamma=scale, svr__kernel=sigmoid;, score=-1.320 total time=   0.1s
[CV 4/5] END svr__C=2000, svr__gamma=scale, svr__kernel=sigmoid;, score=-1.460 total time=   0.0s
[CV 5/5] END svr__C=2000, svr__gamma=scale, svr__kernel=sigmoid;, score=-1.226 total time=   0.0s
[CV 1/5] END svr__C=2000, svr__gamma=scale, svr__kernel=linear;, score=0.672 total time=   0.0s
[CV 2/5] END svr__C=2000, svr__gamma=scale, svr__kernel=linear;, score=0.618 total time=   0.0s
[CV 3/5] END svr__C=2000, svr__gamma=scale, svr__kernel=linear;, score=0.729 total time=   0.0s
[CV 4/5] END svr__C=2000, svr__gamma=scale, svr__kernel=linear;, score=0.628 total time=   0.0s
[CV 5/5] END svr__C=2000, svr__gamma=scale, svr__kernel=linear;, score=0.691 total time=   0.0s
[CV 1/5] END svr__C=3000, svr__gamma=auto, svr__kernel=rbf;, score=0.870 total time=   0.0s
[CV 2/5] END svr__C=3000, svr__gamma=auto, svr__kernel=rbf;, score=0.782 total time=   0.1s
[CV 3/5] END svr__C=3000, svr__gamma=auto, svr__kernel=rbf;, score=0.854 total time=   0.1s
[CV 4/5] END svr__C=3000, svr__gamma=auto, svr__kernel=rbf;, score=0.806 total time=   0.1s
[CV 5/5] END svr__C=3000, svr__gamma=auto, svr__kernel=rbf;, score=0.824 total time=   0.1s
[CV 1/5] END svr__C=3000, svr__gamma=auto, svr__kernel=poly;, score=0.853 total time=   0.2s
[CV 2/5] END svr__C=3000, svr__gamma=auto, svr__kernel=poly;, score=0.774 total time=   0.3s
[CV 3/5] END svr__C=3000, svr__gamma=auto, svr__kernel=poly;, score=0.869 total time=   0.2s
[CV 4/5] END svr__C=3000, svr__gamma=auto, svr__kernel=poly;, score=0.808 total time=   0.1s
[CV 5/5] END svr__C=3000, svr__gamma=auto, svr__kernel=poly;, score=0.810 total time=   0.1s
[CV 1/5] END svr__C=3000, svr__gamma=auto, svr__kernel=sigmoid;, score=-3.535 total time=   0.0s
[CV 2/5] END svr__C=3000, svr__gamma=auto, svr__kernel=sigmoid;, score=-3.969 total time=   0.1s
[CV 3/5] END svr__C=3000, svr__gamma=auto, svr__kernel=sigmoid;, score=-3.644 total time=   0.0s
[CV 4/5] END svr__C=3000, svr__gamma=auto, svr__kernel=sigmoid;, score=-3.364 total time=   0.0s
[CV 5/5] END svr__C=3000, svr__gamma=auto, svr__kernel=sigmoid;, score=-3.648 total time=   0.0s
[CV 1/5] END svr__C=3000, svr__gamma=auto, svr__kernel=linear;, score=0.668 total time=   0.0s

[CV 2/5] END svr__C=3000, svr__gamma=auto, svr__kernel=linear;, score=0.618 total time=   0.0s
[CV 3/5] END svr__C=3000, svr__gamma=auto, svr__kernel=linear;, score=0.729 total time=   0.0s
[CV 4/5] END svr__C=3000, svr__gamma=auto, svr__kernel=linear;, score=0.628 total time=   0.1s
[CV 5/5] END svr__C=3000, svr__gamma=auto, svr__kernel=linear;, score=0.689 total time=   0.0s
[CV 1/5] END svr__C=3000, svr__gamma=scale, svr__kernel=rbf;, score=0.870 total time=   0.1s
[CV 2/5] END svr__C=3000, svr__gamma=scale, svr__kernel=rbf;, score=0.782 total time=   0.1s
[CV 3/5] END svr__C=3000, svr__gamma=scale, svr__kernel=rbf;, score=0.854 total time=   0.1s
[CV 4/5] END svr__C=3000, svr__gamma=scale, svr__kernel=rbf;, score=0.806 total time=   0.1s
[CV 5/5] END svr__C=3000, svr__gamma=scale, svr__kernel=rbf;, score=0.824 total time=   0.1s
[CV 1/5] END svr__C=3000, svr__gamma=scale, svr__kernel=poly;, score=0.853 total time=   0.1s
[CV 2/5] END svr__C=3000, svr__gamma=scale, svr__kernel=poly;, score=0.774 total time=   0.2s
[CV 3/5] END svr__C=3000, svr__gamma=scale, svr__kernel=poly;, score=0.869 total time=   0.2s
[CV 4/5] END svr__C=3000, svr__gamma=scale, svr__kernel=poly;, score=0.808 total time=   0.2s
[CV 5/5] END svr__C=3000, svr__gamma=scale, svr__kernel=poly;, score=0.810 total time=   0.1s
[CV 1/5] END svr__C=3000, svr__gamma=scale, svr__kernel=sigmoid;, score=-3.535 total time=   0.0s
[CV 2/5] END svr__C=3000, svr__gamma=scale, svr__kernel=sigmoid;, score=-3.969 total time=   0.1s
[CV 3/5] END svr__C=3000, svr__gamma=scale, svr__kernel=sigmoid;, score=-3.644 total time=   0.0s
[CV 4/5] END svr__C=3000, svr__gamma=scale, svr__kernel=sigmoid;, score=-3.364 total time=   0.0s
[CV 5/5] END svr__C=3000, svr__gamma=scale, svr__kernel=sigmoid;, score=-3.648 total time=   0.0s
[CV 1/5] END svr__C=3000, svr__gamma=scale, svr__kernel=linear;, score=0.668 total time=   0.0s
[CV 2/5] END svr__C=3000, svr__gamma=scale, svr__kernel=linear;, score=0.618 total time=   0.0s
[CV 3/5] END svr__C=3000, svr__gamma=scale, svr__kernel=linear;, score=0.729 total time=   0.0s
[CV 4/5] END svr__C=3000, svr__gamma=scale, svr__kernel=linear;, score=0.628 total time=   0.0s
[CV 5/5] END svr__C=3000, svr__gamma=scale, svr__kernel=linear;, score=0.689 total time=   0.0s

GridSearchCV(estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('svr', SVR())]),
             n_jobs=1,
             param_grid={'svr__C': [10, 100, 1000, 2000, 3000],
                         'svr__gamma': ['auto', 'scale'],
                         'svr__kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [11]:
# Results
print("Best Parameters:", grid.best_params_)
print("Best Cross-Validated R² Score:", grid.best_score_)
table = pd.DataFrame.from_dict(grid.cv_results_)

Best Parameters: {'svr__C': 3000, 'svr__gamma': 'auto', 'svr__kernel': 'rbf'}
Best Cross-Validated R² Score: 0.8271008960151974

In [12]:
# Prediction (The grid object will now automatically scale your new input!)
age_input = float(input("Age:"))
bmi_input = float(input("BMI:"))
children_input = float(input("Children:"))
sex_male_input = int(input("Sex Male 0 or 1:"))
smoker_yes_input = int(input("Smoker Yes 0 or 1:"))

Age:56
BMI:34
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [15]:
# No need to manually scale this; the pipeline handles it
Future_Prediction = grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[11964.64187728]

C:\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"